// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    YsAlert: typeof import('./components/general/ys-alert/sfc/ys-alert.vue')['default']
    YsMessage: typeof import('./components/general/ys-message/sfc/ys-message.vue')['default']
    YsProgress: typeof import('./components/general/ys-progress/sfc/ys-progress.vue')['default']
    YsUpload: typeof import('./components/general/ys-upload/sfc/ys-upload.vue')['default']
  }
}

export { }
